### ISSUE TITLE
Create Snap Package and Snapcraft Configuration

### ISSUE THREAD

**Issue by filinvadim** [Warp-net/warpnet#18]
To simplify distribution, installation, and updates of the WarpNet node on Linux systems, we should provide an official Snap package.

This will make the node:
- Easy to install via `snap install warpnet`,
- Auto-updatable through Snapcraft channels,
- Sandboxed and declaratively configured,
- Portable across many Linux distributions (Ubuntu, Fedora, Arch, etc).

Tasks:

1. Create `snapcraft.yaml` with:
   * Go build instructions,
   * Required binaries and assets,
   * Daemon/service definition (if needed),
   * Required interfaces (e.g. `network`, `home`, `network-bind`, `process-control`, etc.),
   * Confinement: likely `classic` or `strict` with plugs.

2. Build and test snap locally:
   * `snapcraft --use-lxd`
   * `snap install --dangerous ./warpnet.snap`

3. Test runtime behavior:
   * Can bind to ports,
   * Can access data directories,
   * Can discover and communicate with other peers.

4. Publish to Snap Store:
   * Set up Snapcraft account,
   * Push to edge channel,
   * Document installation instructions.

---

### Example snapcraft.yaml (simplified):

```yaml
name: warpnet
base: core22
version: '0.1.0'
summary: Distributed social node
description: |
  WarpNet is a decentralized social networking node.

grade: stable
confinement: classic

apps:
  warpnetd:
    command: bin/warpnet
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  warpnet:
    plugin: go
    source: .
    build-snaps:
      - go
```

Looking for help from those familiar with Snap packaging or Snap Store publishing.
